#!/bin/bash
[[ "$EUID" != 0 ]] && sudo -v
scriptPID=$$
scriptPath="$(dirname "$0")"
scriptName="$(basename "$0")"
usage="Usage: $scriptName file"
tvPath="/mnt/nas/Media/TV Shows"
tvRegex='(^.+)\ \-\ S([0-9][0-9])(E[0-9][0-9].*$)'

log(){ 
    echo "[$(date +%F\ %T)] $(whoami) ($scriptPID) $scriptName - $@" >>/var/log/ingest.log
    logger -i "$scriptName - $@"
}
Test(){
    if [[ "$(basename "$1")" =~ $tvRegex ]]; then
        remote="$tvPath/${BASH_REMATCH[1]}/Season ${BASH_REMATCH[2]#0*}/${BASH_REMATCH[1]} - S${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
        if [ -e "$remote" ]; then 
            echo "Original File:    $(du -h "$1")"
            echo "Remote File:      $(du -h "$remote")"
        else
            echo "Remote file doesnt exist at $remote"
            return 1
        fi
    else
        echo "Error: $1 doesnt conform to regex pattern: $tvRegex"
        return 1
    fi
}
Move(){

    if [[ "$(basename "$1")" =~ $tvRegex ]]; then
        series=${BASH_REMATCH[1]}
        season=${BASH_REMATCH[2]#0*}
        path="$tvPath/$series/Season $season"
        if [ ! -d "$path" ]; then
            mkdir -p "$path"
            chmod 0777 "$path"
        fi
        error=$(cp -vf "$1" "$path" 2>&1 && sudo rm "$1" 2>&1);
        [ $? -eq 0 ] \
            && log "Moved $1 to $tvPath" \
            || log "Error: $error"; 
    else
        echo $1 didnt match
        return 1
    fi
}

if [ $# -eq 0 ]; then 
    echo "$usage"
    exit 1
fi 

while [ ${#@} -gt 0 ]; do
    case "$1" in
    --help    | -h ) echo "$usage"; exit 0;;
    --test    | -t ) Test "$2"; exit 0;;
    * ) Move "$1";;
    esac
    shift
done    
